"""
Schemas package — re-exports all Pydantic schemas.

Importing from `schemas` continues to work as before:
    from schemas import Recipe, RecipeCreate, User, ...
"""

from schemas.user import (
    UserBase,
    UserCreate,
    UserLogin,
    User,
    Token,
    TokenData,
    RefreshTokenRequest,
    UserUpdate,
    PasswordChange,
    UserProfileUpdate,
    UserProfile,
    NotificationBase,
    NotificationCreate,
    Notification,
    NotificationMarkRead,
    PublicUserProfile,
    ShareableUser,
    UserSearchResult,
    UserFollowBase,
    UserFollow,
    FollowRequest,
    FollowResponse,
    UserProfilePublic,
    UserSettingsBase,
    UserSettingsUpdate,
    UserSettings,
)

from schemas.recipe import (
    RecipeIngredientBase,
    RecipeIngredientCreate,
    RecipeIngredient,
    RecipeInstructionBase,
    RecipeInstructionCreate,
    RecipeInstruction,
    TagBase,
    TagCreate,
    Tag,
    CollectionBase,
    CollectionCreate,
    CollectionUpdate,
    Collection,
    CollectionWithRecipes,
    CollectionShareCreate,
    CollectionShareUpdate,
    CollectionShareUser,
    CollectionShare,
    SharedCollection,
    RecipeBase,
    RecipeCreate,
    RecipeUpdate,
    RecipeAuthor,
    CollectionInfo,
    RecipeSummary,
    ForkedFromInfo,
    ClonedByMeInfo,
    SubRecipeInput,
    SubRecipeInfo,
    Recipe,
    RecipeWithScale,
    IngredientBase,
    IngredientCreate,
    IngredientUpdate,
    Ingredient,
    MeasurementUnitBase,
    MeasurementUnit,
    ParsedIngredient,
    IngredientParseRequest,
    IngredientParseResponse,
    PaginatedResponse,
    RecipeListResponse,
    RecipeImportRequest,
    RecipeParseTextRequest,
    ImportedIngredient,
    ImportedInstruction,
    RecipeImportResponse,
    RecipeImportMultiResponse,
)

from schemas.meal_plan import (
    MealPlanCalendarCreate,
    MealPlanCalendarUpdate,
    MealPlanCalendarSummary,
    MealPlanCreate,
    MealPlanUpdate,
    MealPlanMove,
    MealPlanCopy,
    MealPlanRecurring,
    MealPlanRecipe,
    MealPlan,
    MealPlanListResponse,
    MealPlanShareUser,
    MealPlanCalendarShareCreate,
    MealPlanCalendarShareUpdate,
    MealPlanCalendarShareResponse,
    SharedMealPlanOwner,
    SharedMealPlanCalendarAccess,
    # Deprecated aliases
    MealPlanShareCreate,
    MealPlanShareUpdate,
    MealPlanShareResponse,
    SharedMealPlanAccess,
)

from schemas.grocery import (
    GroceryListItemCreate,
    GroceryListItemUpdate,
    SourceRecipeInfo,
    GroceryListItemResponse,
    GroceryListShareUser,
    GroceryListCreate,
    GroceryListUpdate,
    GroceryListSummary,
    GroceryListShareCreate,
    GroceryListShareUpdate,
    GroceryListShareResponse,
    GroceryListResponse,
    GroceryListGenerateRequest,
    GroceryListBulkCheckRequest,
    SharedGroceryListOwner,
    SharedGroceryListAccess,
    GroceryListEmailShareRequest,
    GroceryListEmailShareResponse,
    GroceryListAcceptPublicShareResponse,
)

from schemas.library import (
    LibraryShareCreate,
    LibraryShareResponse,
    LibraryPartner,
    PendingLibraryInvite,
)

__all__ = [
    # user
    "UserBase", "UserCreate", "UserLogin", "User", "Token", "TokenData",
    "RefreshTokenRequest", "UserUpdate", "PasswordChange", "UserProfileUpdate",
    "UserProfile", "NotificationBase", "NotificationCreate", "Notification",
    "NotificationMarkRead", "PublicUserProfile", "ShareableUser",
    "UserSearchResult", "UserFollowBase", "UserFollow", "FollowRequest",
    "FollowResponse", "UserProfilePublic", "UserSettingsBase",
    "UserSettingsUpdate", "UserSettings",
    # recipe
    "RecipeIngredientBase", "RecipeIngredientCreate", "RecipeIngredient",
    "RecipeInstructionBase", "RecipeInstructionCreate", "RecipeInstruction",
    "TagBase", "TagCreate", "Tag", "CollectionBase", "CollectionCreate",
    "CollectionUpdate", "Collection", "CollectionWithRecipes",
    "CollectionShareCreate", "CollectionShareUpdate", "CollectionShareUser",
    "CollectionShare", "SharedCollection", "RecipeBase", "RecipeCreate",
    "RecipeUpdate", "RecipeAuthor", "CollectionInfo", "RecipeSummary",
    "ForkedFromInfo", "ClonedByMeInfo", "SubRecipeInput", "SubRecipeInfo",
    "Recipe", "RecipeWithScale", "IngredientBase", "IngredientCreate",
    "IngredientUpdate", "Ingredient", "MeasurementUnitBase", "MeasurementUnit",
    "ParsedIngredient", "IngredientParseRequest", "IngredientParseResponse",
    "PaginatedResponse", "RecipeListResponse", "RecipeImportRequest",
    "RecipeParseTextRequest", "ImportedIngredient", "ImportedInstruction",
    "RecipeImportResponse", "RecipeImportMultiResponse",
    # meal_plan
    "MealPlanCalendarCreate", "MealPlanCalendarUpdate", "MealPlanCalendarSummary",
    "MealPlanCreate", "MealPlanUpdate", "MealPlanMove", "MealPlanCopy",
    "MealPlanRecurring", "MealPlanRecipe", "MealPlan", "MealPlanListResponse",
    "MealPlanShareUser", "MealPlanCalendarShareCreate", "MealPlanCalendarShareUpdate",
    "MealPlanCalendarShareResponse", "SharedMealPlanOwner",
    "SharedMealPlanCalendarAccess", "MealPlanShareCreate", "MealPlanShareUpdate",
    "MealPlanShareResponse", "SharedMealPlanAccess",
    # grocery
    "GroceryListItemCreate", "GroceryListItemUpdate", "SourceRecipeInfo",
    "GroceryListItemResponse", "GroceryListShareUser", "GroceryListCreate",
    "GroceryListUpdate", "GroceryListSummary", "GroceryListShareCreate",
    "GroceryListShareUpdate", "GroceryListShareResponse", "GroceryListResponse",
    "GroceryListGenerateRequest", "GroceryListBulkCheckRequest",
    "SharedGroceryListOwner", "SharedGroceryListAccess",
    "GroceryListEmailShareRequest", "GroceryListEmailShareResponse",
    "GroceryListAcceptPublicShareResponse",
    # library
    "LibraryShareCreate", "LibraryShareResponse", "LibraryPartner",
    "PendingLibraryInvite",
]
